"""Python-native build orchestration for generated SRK Saturn projects.

The SH-ELF tools remain the actual compiler/assembler/linker backend. Python
replaces the fragile historical make/shell orchestration: every child process is
invoked directly with an argv list, PATH is not mutated, source/input hashes are
checked before and after the build, and one immutable-style build report is
published into the generated project.

The ISO9660 image produced by mkisofs is retained as an internal verification
artifact. SRK reopens that image read-only to prove the deterministic packaged
PCM file has the exact generated bytes before converting the ISO to a verified
single-track MODE1/2352 BIN/CUE pair for the guarded SAROO deployment workflow.

Stage 6B additionally compiles against and links the caller's installed SBL 6.01
GFS/CDC artifacts by their pinned absolute paths. Those private SDK files remain
outside the generated project and are SHA-256 verified before and after build.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
import json
import os
import shutil
import subprocess
from typing import Callable, Sequence

from rikai_kotoba.core.disc_image import DiscImage, DiscImageError
from rikai_kotoba.core.iso9660 import ISO9660Error, ISO9660Reader
from rikai_kotoba.formats.saturn.mode1_image import (
    SaturnMode1ImageError,
    SaturnMode1ImageResult,
    write_single_track_mode1_bin_cue,
)
from rikai_kotoba.formats.saturn.packaged_pcm import (
    PACKAGED_PCM_FILENAME,
    SaturnPackagedPCMError,
    parse_packaged_pcm,
)


class SaturnStandaloneBuildError(RuntimeError):
    """Raised when a generated standalone project cannot be built safely."""


@dataclass(frozen=True)
class SaturnStandaloneBuildArtifact:
    path: Path
    size: int
    sha256: str


@dataclass(frozen=True)
class SaturnStandaloneBuildCommand:
    label: str
    argv: tuple[str, ...]
    returncode: int
    output: str


@dataclass(frozen=True)
class SaturnPackagedPCMVerification:
    project_path: Path
    iso_path: str
    extent_lba: int
    size: int
    sha256: str
    sample_count: int
    loop_start: int
    loop_end: int


@dataclass(frozen=True)
class SaturnStandaloneBuildResult:
    project_root: Path
    log_path: Path
    report_path: Path
    commands: tuple[SaturnStandaloneBuildCommand, ...]
    artifacts: tuple[SaturnStandaloneBuildArtifact, ...]
    successful: bool


_C_SOURCES = (
    "srk_saturn_main.c",
    "srk_saturn_host.c",
    "srk_saturn_audio.c",
    "srk_saturn_packaged_pcm.c",
    "srk_diag_app.c",
    "srk_diag_audio.c",
    "srk_diag_input.c",
    "srk_diag_menu.c",
    "srk_diag_flight_recorder.c",
    "srk_diag_vdp1.c",
    "srk_diag_video.c",
)

_OBJECTS = tuple(f"build/{Path(source).stem}.o" for source in _C_SOURCES)
_STARTUP_OBJECT = "build/srk_saturn_startup.o"
_MANIFEST_NAME = "SRK_STANDALONE_PROJECT.json"
_REPORT_NAME = "SRK_STANDALONE_BUILD.json"
_LOG_NAME = "SRK_STANDALONE_BUILD_LOG.txt"
_DEPLOY_DIRECTORY = "build/SRK-Diagnostics"
_DEPLOY_BIN = f"{_DEPLOY_DIRECTORY}/SRK-Diagnostics.bin"
_DEPLOY_CUE = f"{_DEPLOY_DIRECTORY}/SRK-Diagnostics.cue"


def _canonical(path: os.PathLike[str] | str) -> Path:
    return Path(path).expanduser().resolve(strict=False)


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _load_manifest(root: Path) -> dict:
    path = root / _MANIFEST_NAME
    if not path.is_file():
        raise SaturnStandaloneBuildError(f"project manifest is missing: {path}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SaturnStandaloneBuildError(f"cannot read project manifest: {exc}") from exc
    if data.get("schema") != "srk.saturn.standalone-project.v1":
        raise SaturnStandaloneBuildError("unsupported standalone project manifest schema")
    if data.get("mode") != "standalone-master":
        raise SaturnStandaloneBuildError("project manifest is not standalone-master mode")
    return data


def _verify_generated_inputs(root: Path, manifest: dict) -> None:
    entries = manifest.get("generated_files")
    if not isinstance(entries, list) or not entries:
        raise SaturnStandaloneBuildError("project manifest has no generated file inventory")

    for entry in entries:
        if not isinstance(entry, dict):
            raise SaturnStandaloneBuildError("invalid generated file inventory entry")
        relative = entry.get("path")
        expected = entry.get("sha256")
        if not isinstance(relative, str) or not isinstance(expected, str):
            raise SaturnStandaloneBuildError("invalid generated file inventory metadata")
        path = root / relative
        if not path.is_file():
            raise SaturnStandaloneBuildError(f"generated project input is missing: {relative}")
        actual = _sha256_file(path)
        if actual.lower() != expected.lower():
            raise SaturnStandaloneBuildError(
                f"generated project input hash mismatch: {relative}; "
                f"expected {expected}, got {actual}"
            )


def _verify_private_dependency(entry: object, label: str) -> Path:
    if not isinstance(entry, dict):
        raise SaturnStandaloneBuildError(f"Stage 6B manifest has no {label} metadata")
    path_text = entry.get("path")
    expected_size = entry.get("size")
    expected_sha = entry.get("sha256")
    if not isinstance(path_text, str) or not path_text:
        raise SaturnStandaloneBuildError(f"Stage 6B {label} path is invalid")
    if not isinstance(expected_size, int) or expected_size <= 0:
        raise SaturnStandaloneBuildError(f"Stage 6B {label} size is invalid")
    if not isinstance(expected_sha, str) or len(expected_sha) != 64:
        raise SaturnStandaloneBuildError(f"Stage 6B {label} SHA-256 is invalid")

    path = _canonical(path_text)
    if not path.is_file():
        raise SaturnStandaloneBuildError(f"Stage 6B {label} is missing: {path}")
    if path.stat().st_size != expected_size:
        raise SaturnStandaloneBuildError(
            f"Stage 6B {label} size changed: expected {expected_size}, got {path.stat().st_size}"
        )
    actual_sha = _sha256_file(path)
    if actual_sha.lower() != expected_sha.lower():
        raise SaturnStandaloneBuildError(
            f"Stage 6B {label} hash changed: expected {expected_sha}, got {actual_sha}"
        )
    return path


def _stage6b_gfs_dependencies(manifest: dict) -> tuple[Path, Path, Path, Path]:
    metadata = manifest.get("stage6b_gfs")
    if not isinstance(metadata, dict):
        raise SaturnStandaloneBuildError("project manifest has no stage6b_gfs metadata")
    if metadata.get("copied_into_project") is not False:
        raise SaturnStandaloneBuildError("Stage 6B private dependencies must remain external")

    include_text = metadata.get("include_dir")
    if not isinstance(include_text, str) or not include_text:
        raise SaturnStandaloneBuildError("Stage 6B GFS include directory is invalid")
    include_dir = _canonical(include_text)
    if not include_dir.is_dir():
        raise SaturnStandaloneBuildError(
            f"Stage 6B GFS include directory is missing: {include_dir}"
        )

    gfs_header = _verify_private_dependency(metadata.get("gfs_header"), "GFS header")
    gfs_library = _verify_private_dependency(metadata.get("gfs_library"), "GFS library")
    cdc_library = _verify_private_dependency(metadata.get("cdc_library"), "CDC library")
    if gfs_header.parent != include_dir:
        raise SaturnStandaloneBuildError(
            "Stage 6B GFS header is not inside the pinned include directory"
        )
    return include_dir, gfs_header, gfs_library, cdc_library


def _packaged_pcm_manifest(root: Path, manifest: dict) -> tuple[Path, dict]:
    metadata = manifest.get("packaged_pcm")
    if not isinstance(metadata, dict):
        raise SaturnStandaloneBuildError("project manifest has no packaged_pcm metadata")

    relative = metadata.get("path")
    expected_size = metadata.get("size")
    expected_sha = metadata.get("sha256")
    if not isinstance(relative, str) or relative != f"cd/{PACKAGED_PCM_FILENAME}":
        raise SaturnStandaloneBuildError("project manifest packaged PCM path is invalid")
    if not isinstance(expected_size, int) or expected_size <= 0:
        raise SaturnStandaloneBuildError("project manifest packaged PCM size is invalid")
    if not isinstance(expected_sha, str) or len(expected_sha) != 64:
        raise SaturnStandaloneBuildError("project manifest packaged PCM SHA-256 is invalid")

    path = root / relative
    if not path.is_file():
        raise SaturnStandaloneBuildError(f"packaged PCM is missing: {relative}")
    if path.stat().st_size != expected_size:
        raise SaturnStandaloneBuildError(
            f"packaged PCM size mismatch: expected {expected_size}, got {path.stat().st_size}"
        )
    actual_sha = _sha256_file(path)
    if actual_sha.lower() != expected_sha.lower():
        raise SaturnStandaloneBuildError(
            f"packaged PCM hash mismatch: expected {expected_sha}, got {actual_sha}"
        )
    try:
        parse_packaged_pcm(path.read_bytes())
    except SaturnPackagedPCMError as exc:
        raise SaturnStandaloneBuildError(f"packaged PCM format is invalid: {exc}") from exc
    return path, metadata


def _verify_packaged_pcm_in_iso(
    root: Path,
    manifest: dict,
    iso_path: Path,
) -> SaturnPackagedPCMVerification:
    project_path, metadata = _packaged_pcm_manifest(root, manifest)
    project_bytes = project_path.read_bytes()

    image = DiscImage(iso_path)
    reader = ISO9660Reader(image)
    entry = reader.get_entry(f"/{PACKAGED_PCM_FILENAME}")
    iso_bytes = reader.read_file(entry)

    if entry.is_dir:
        raise SaturnStandaloneBuildError("packaged PCM ISO entry is unexpectedly a directory")
    if entry.size != len(project_bytes):
        raise SaturnStandaloneBuildError(
            f"packaged PCM ISO size mismatch: expected {len(project_bytes)}, got {entry.size}"
        )
    if iso_bytes != project_bytes:
        raise SaturnStandaloneBuildError(
            "packaged PCM bytes inside ISO do not match the generated project payload"
        )

    actual_sha = sha256(iso_bytes).hexdigest()
    expected_sha = str(metadata["sha256"])
    if actual_sha.lower() != expected_sha.lower():
        raise SaturnStandaloneBuildError(
            f"packaged PCM ISO SHA-256 mismatch: expected {expected_sha}, got {actual_sha}"
        )

    parsed = parse_packaged_pcm(iso_bytes)
    return SaturnPackagedPCMVerification(
        project_path=project_path,
        iso_path=f"/{entry.raw_name}",
        extent_lba=entry.lba,
        size=entry.size,
        sha256=actual_sha,
        sample_count=parsed.sample_count,
        loop_start=parsed.loop_start,
        loop_end=parsed.loop_end,
    )


def _tool(manifest: dict, key: str) -> Path:
    tools = manifest.get("tools")
    if not isinstance(tools, dict):
        raise SaturnStandaloneBuildError("project manifest has no tool inventory")
    value = tools.get(key)
    if not isinstance(value, str) or not value:
        raise SaturnStandaloneBuildError(f"project manifest has no {key} tool path")
    path = _canonical(value)
    if not path.is_file():
        raise SaturnStandaloneBuildError(f"recorded {key} tool does not exist: {path}")
    return path


def _decode_output(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return str(value)


def _artifact(path: Path) -> SaturnStandaloneBuildArtifact:
    return SaturnStandaloneBuildArtifact(
        path=path,
        size=path.stat().st_size,
        sha256=_sha256_file(path),
    )


def _write_log(path: Path, commands: Sequence[SaturnStandaloneBuildCommand]) -> None:
    lines: list[str] = []
    for command in commands:
        lines.append(f"[{command.label}] returncode={command.returncode}")
        lines.append("argv: " + " ".join(command.argv))
        if command.output:
            lines.append(command.output.rstrip())
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def _write_report(
    path: Path,
    root: Path,
    manifest_path: Path,
    commands: Sequence[SaturnStandaloneBuildCommand],
    artifacts: Sequence[SaturnStandaloneBuildArtifact],
    successful: bool,
    inputs_verified_after: bool,
    private_dependencies_verified_after: bool,
    mode1_result: SaturnMode1ImageResult | None,
    packaged_pcm: SaturnPackagedPCMVerification | None,
) -> None:
    data = {
        "schema": "srk.saturn.standalone-build.v1",
        "project_root": str(root),
        "project_manifest_sha256": _sha256_file(manifest_path),
        "orchestration": "python-native",
        "successful": bool(successful),
        "policy": {
            "shell_used": False,
            "path_mutated": False,
            "source_inputs_verified_before_build": True,
            "source_inputs_verified_after_build": bool(inputs_verified_after),
            "private_sdk_dependencies_verified_before_build": True,
            "private_sdk_dependencies_verified_after_build": bool(
                private_dependencies_verified_after
            ),
            "private_sdk_dependencies_copied": False,
            "sd_writes": False,
            "commercial_image_changes": False,
        },
        "commands": [
            {
                "label": command.label,
                "argv": list(command.argv),
                "returncode": command.returncode,
            }
            for command in commands
        ],
        "artifacts": [
            {
                "path": artifact.path.relative_to(root).as_posix(),
                "size": artifact.size,
                "sha256": artifact.sha256,
            }
            for artifact in artifacts
        ],
    }
    if packaged_pcm is not None:
        data["packaged_pcm"] = {
            "project_path": packaged_pcm.project_path.relative_to(root).as_posix(),
            "iso_path": packaged_pcm.iso_path,
            "iso_extent_lba": packaged_pcm.extent_lba,
            "size": packaged_pcm.size,
            "sha256": packaged_pcm.sha256,
            "sample_count": packaged_pcm.sample_count,
            "loop_start": packaged_pcm.loop_start,
            "loop_end": packaged_pcm.loop_end,
            "verified_against_project": True,
        }
    if mode1_result is not None:
        data["deployable"] = {
            "format": "cue-bin-mode1-2352",
            "cue": mode1_result.cue_path.relative_to(root).as_posix(),
            "bin": mode1_result.bin_path.relative_to(root).as_posix(),
            "sector_count": mode1_result.sector_count,
            "user_bytes": mode1_result.user_bytes,
            "raw_bytes": mode1_result.raw_bytes,
            "verified_against_iso": True,
        }
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build_saturn_standalone_project(
    project_directory: os.PathLike[str] | str,
    *,
    _runner: Callable[..., object] | None = None,
) -> SaturnStandaloneBuildResult:
    """Build one fresh generated Saturn project without make or shell scripts."""

    root = _canonical(project_directory)
    if not root.is_dir():
        raise SaturnStandaloneBuildError(f"project directory is not a directory: {root}")

    manifest_path = root / _MANIFEST_NAME
    report_path = root / _REPORT_NAME
    log_path = root / _LOG_NAME
    if report_path.exists() or log_path.exists():
        raise SaturnStandaloneBuildError(
            "Python-native build provenance already exists; generate a fresh project tree"
        )

    manifest = _load_manifest(root)
    _verify_generated_inputs(root, manifest)
    _packaged_pcm_manifest(root, manifest)
    gfs_include, _gfs_header, gfs_library, cdc_library = _stage6b_gfs_dependencies(manifest)

    gcc = _tool(manifest, "sh-elf-gcc")
    assembler = _tool(manifest, "sh-elf-as")
    iso_builder = _tool(manifest, "iso-builder")

    build_dir = root / "build"
    cd_dir = root / "cd"
    build_dir.mkdir(exist_ok=True)
    cd_dir.mkdir(exist_ok=True)
    if any(build_dir.iterdir()) or (cd_dir / "0.bin").exists():
        raise SaturnStandaloneBuildError(
            "build outputs already exist; generate a fresh project tree to preserve provenance"
        )

    runner = _runner or subprocess.run
    commands: list[SaturnStandaloneBuildCommand] = []

    def invoke(label: str, argv: Sequence[str]) -> bool:
        completed = runner(
            [str(item) for item in argv],
            cwd=str(root),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
            shell=False,
        )
        returncode = int(getattr(completed, "returncode", 1))
        output = _decode_output(getattr(completed, "stdout", b""))
        commands.append(
            SaturnStandaloneBuildCommand(
                label=label,
                argv=tuple(str(item) for item in argv),
                returncode=returncode,
                output=output,
            )
        )
        return returncode == 0

    compile_flags = (
        "-Wall",
        "-Werror",
        "-m2",
        "-O0",
        "-ffreestanding",
        "-fno-builtin",
        "-Isrc",
        f"-I{gfs_include}",
    )

    successful = True
    for source in _C_SOURCES:
        obj = f"build/{Path(source).stem}.o"
        argv = (str(gcc), "-c", f"src/{source}", "-o", obj, *compile_flags)
        if not invoke(f"compile {source}", argv):
            successful = False
            break

    if successful:
        successful = invoke(
            "assemble startup",
            (str(assembler), "src/srk_saturn_startup.S", "-o", _STARTUP_OBJECT),
        )

    if successful:
        link_argv = (
            str(gcc),
            "-nostdlib",
            "-m2",
            "-Wl,--script,srk_saturn.ld",
            "-Wl,-Map,build/srk_diag.map",
            "-o",
            "build/srk_diag.bin",
            _STARTUP_OBJECT,
            *_OBJECTS,
            str(gfs_library),
            str(cdc_library),
            "-lgcc",
        )
        successful = invoke("link binary", link_argv)

    binary = build_dir / "srk_diag.bin"
    if successful:
        if not binary.is_file() or binary.stat().st_size <= 0:
            successful = False
            commands.append(
                SaturnStandaloneBuildCommand(
                    label="verify binary",
                    argv=tuple(),
                    returncode=1,
                    output="link command returned success but build/srk_diag.bin is missing or empty",
                )
            )
        else:
            shutil.copy2(binary, cd_dir / "0.bin")

    if successful:
        iso_prefix: tuple[str, ...] = (str(iso_builder),)
        if iso_builder.name.casefold().startswith("xorriso"):
            iso_prefix = (str(iso_builder), "-as", "mkisofs")
        iso_argv = (
            *iso_prefix,
            "-quiet",
            "-sysid", "SEGA SATURN",
            "-volid", "SRKDIAG",
            "-volset", "SRKDIAG",
            "-publisher", "SRK PROJECT",
            "-preparer", "SRK",
            "-appid", "SRK SATURN DIAGNOSTICS",
            "-generic-boot", "IP.BIN",
            "-full-iso9660-filenames",
            "-o", "build/srk_diag.iso",
            "cd",
        )
        successful = invoke("package ISO", iso_argv)

    iso = build_dir / "srk_diag.iso"
    if successful and (not iso.is_file() or iso.stat().st_size <= 0):
        successful = False
        commands.append(
            SaturnStandaloneBuildCommand(
                label="verify ISO",
                argv=tuple(),
                returncode=1,
                output="ISO builder returned success but build/srk_diag.iso is missing or empty",
            )
        )

    packaged_pcm_verification: SaturnPackagedPCMVerification | None = None
    if successful:
        try:
            packaged_pcm_verification = _verify_packaged_pcm_in_iso(root, manifest, iso)
            commands.append(
                SaturnStandaloneBuildCommand(
                    label="verify packaged PCM in ISO",
                    argv=tuple(),
                    returncode=0,
                    output=(
                        f"{packaged_pcm_verification.iso_path} at LBA "
                        f"{packaged_pcm_verification.extent_lba}; "
                        f"{packaged_pcm_verification.size} bytes; SHA-256 "
                        f"{packaged_pcm_verification.sha256}"
                    ),
                )
            )
        except (
            OSError,
            DiscImageError,
            ISO9660Error,
            SaturnPackagedPCMError,
            SaturnStandaloneBuildError,
        ) as exc:
            successful = False
            commands.append(
                SaturnStandaloneBuildCommand(
                    label="verify packaged PCM in ISO",
                    argv=tuple(),
                    returncode=1,
                    output=str(exc),
                )
            )

    mode1_result: SaturnMode1ImageResult | None = None
    if successful:
        deploy_dir = root / _DEPLOY_DIRECTORY
        deploy_dir.mkdir(parents=True, exist_ok=False)
        try:
            mode1_result = write_single_track_mode1_bin_cue(
                iso,
                root / _DEPLOY_BIN,
                root / _DEPLOY_CUE,
            )
            commands.append(
                SaturnStandaloneBuildCommand(
                    label="package MODE1/2352 BIN/CUE",
                    argv=tuple(),
                    returncode=0,
                    output=(
                        f"{mode1_result.sector_count} sectors; "
                        f"{mode1_result.raw_bytes} raw bytes; verified against ISO"
                    ),
                )
            )
        except (OSError, SaturnMode1ImageError) as exc:
            successful = False
            commands.append(
                SaturnStandaloneBuildCommand(
                    label="package MODE1/2352 BIN/CUE",
                    argv=tuple(),
                    returncode=1,
                    output=str(exc),
                )
            )

    inputs_verified_after = False
    private_dependencies_verified_after = False
    if successful:
        try:
            _verify_generated_inputs(root, manifest)
            _packaged_pcm_manifest(root, manifest)
            _stage6b_gfs_dependencies(manifest)
            inputs_verified_after = True
            private_dependencies_verified_after = True
        except SaturnStandaloneBuildError as exc:
            successful = False
            commands.append(
                SaturnStandaloneBuildCommand(
                    label="verify generated/private inputs",
                    argv=tuple(),
                    returncode=1,
                    output=str(exc),
                )
            )

    artifacts: list[SaturnStandaloneBuildArtifact] = []
    for relative in (
        "build/srk_diag.bin",
        "build/srk_diag.iso",
        "build/srk_diag.map",
        "cd/0.bin",
        f"cd/{PACKAGED_PCM_FILENAME}",
        _DEPLOY_BIN,
        _DEPLOY_CUE,
    ):
        path = root / relative
        if path.is_file():
            artifacts.append(_artifact(path))

    _write_log(log_path, commands)
    _write_report(
        report_path,
        root,
        manifest_path,
        commands,
        artifacts,
        successful,
        inputs_verified_after,
        private_dependencies_verified_after,
        mode1_result if successful else None,
        packaged_pcm_verification if successful else None,
    )

    return SaturnStandaloneBuildResult(
        project_root=root,
        log_path=log_path,
        report_path=report_path,
        commands=tuple(commands),
        artifacts=tuple(artifacts),
        successful=successful,
    )