#ifndef SRK_SATURN_MIDI_68K_COMMAND_STATE_H
#define SRK_SATURN_MIDI_68K_COMMAND_STATE_H

/* Silent command/state contract only. No SCSP voice writes are enabled. */
#define SRK_MIDI_68K_STATE_ADDRESS 0x00001200UL
#define SRK_MIDI_68K_CHANNEL_COUNT 16u
#define SRK_MIDI_68K_CHANNEL_STATE_WORDS 16u
#define SRK_MIDI_68K_CHANNEL_STATE_BYTES 32u
#define SRK_MIDI_68K_CONTROLLER_ADDRESS 0x00001400UL
#define SRK_MIDI_68K_CONTROLLER_COUNT 128u
#define SRK_MIDI_68K_ACTIVE_NOTES_ADDRESS 0x00001C00UL
#define SRK_MIDI_68K_ACTIVE_NOTE_BYTES_PER_CHANNEL 16u
#define SRK_MIDI_68K_TELEMETRY_ADDRESS 0x00001D00UL
#define SRK_MIDI_68K_TELEMETRY_BYTES 256u

#define SRK_MIDI_68K_CH_PROGRAM 0u
#define SRK_MIDI_68K_CH_BANK_MSB 1u
#define SRK_MIDI_68K_CH_BANK_LSB 2u
#define SRK_MIDI_68K_CH_VOLUME 3u
#define SRK_MIDI_68K_CH_PAN 4u
#define SRK_MIDI_68K_CH_EXPRESSION 5u
#define SRK_MIDI_68K_CH_SUSTAIN 6u
#define SRK_MIDI_68K_CH_CHANNEL_PRESSURE 7u
#define SRK_MIDI_68K_CH_PITCH_BEND 8u
#define SRK_MIDI_68K_CH_LAST_NOTE 9u
#define SRK_MIDI_68K_CH_LAST_VELOCITY 10u
#define SRK_MIDI_68K_CH_LAST_POLY_NOTE 11u
#define SRK_MIDI_68K_CH_LAST_POLY_PRESSURE 12u
#define SRK_MIDI_68K_CH_ACTIVE_NOTE_COUNT 13u
#define SRK_MIDI_68K_CH_EVENT_COUNT 14u
#define SRK_MIDI_68K_CH_LAST_OPCODE 15u
#define SRK_MIDI_68K_NO_NOTE 0xFFFFu

#endif
