#ifndef SRK_SATURN_MIDI_GENERATED_H
#define SRK_SATURN_MIDI_GENERATED_H

/* Generated by SRK. Hardware launch is not enabled by this file. */
#define SRK_MIDI_MAILBOX_ADDRESS 0x00001000UL
#define SRK_MIDI_MAILBOX_BYTES 0x00000100UL
#define SRK_MIDI_QUEUE_ADDRESS 0x00001100UL
#define SRK_MIDI_QUEUE_CAPACITY 32u
#define SRK_MIDI_QUEUE_RECORD_BYTES 8u
#define SRK_MIDI_TONE_BANK_ADDRESS 0x00003000UL
#define SRK_MIDI_TONE_COUNT 3u
#define SRK_MIDI_TONE_SAMPLES 64u
#define SRK_MIDI_EVENT_COUNT 27UL
#define SRK_MIDI_DURATION_US 1800000UL

#define SRK_MIDI_MAILBOX_MAGIC0 0x5352u
#define SRK_MIDI_MAILBOX_MAGIC1 0x4B4Du
#define SRK_MIDI_MAILBOX_VERSION 1u
#define SRK_MIDI_MB_MAGIC0 0u
#define SRK_MIDI_MB_MAGIC1 1u
#define SRK_MIDI_MB_VERSION 2u
#define SRK_MIDI_MB_FLAGS 3u
#define SRK_MIDI_MB_WRITE_SEQUENCE 4u
#define SRK_MIDI_MB_READ_SEQUENCE 5u
#define SRK_MIDI_MB_WRITE_INDEX 6u
#define SRK_MIDI_MB_READ_INDEX 7u
#define SRK_MIDI_MB_QUEUE_CAPACITY 8u
#define SRK_MIDI_MB_QUEUE_COUNT 9u
#define SRK_MIDI_MB_LAST_ERROR 10u
#define SRK_MIDI_MB_RESERVED 11u

typedef struct SRK_SATURN_MIDI_EVENT {
    unsigned long time_us;
    unsigned char opcode;
    unsigned char channel;
    unsigned char data0;
    unsigned char data1;
} SRK_SATURN_MIDI_EVENT;

extern const SRK_SATURN_MIDI_EVENT srk_saturn_midi_events[SRK_MIDI_EVENT_COUNT];
extern const unsigned short srk_saturn_midi_tone_bank[SRK_MIDI_TONE_COUNT][SRK_MIDI_TONE_SAMPLES];

#endif
